import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { dbConnect } from '@/db/dbConnect';
import { auth } from '@/auth';


const leto = Lato({
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Book Room",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect();
  const session = await auth();
  console.log(session)
  return (
    <html lang="en">
      <body className={`${leto.className} antialiased`}>
        <Navbar />
        <div className="px-3 py-3">{children}</div>
      </body>
    </html>
  );
}
